-- ============================================================
-- LUWA GLOBAL VISIT ANALYTICS - SUPABASE SETUP
-- Run this ONCE in Supabase Dashboard > SQL Editor.
-- Stores approximate city/country/coarse coordinates only.
-- It does NOT store visitor IP addresses.
-- ============================================================

create table if not exists public.luwa_visit_events (
  id bigint generated by default as identity primary key,
  city text not null,
  country text not null,
  country_code text,
  lat double precision not null,
  lng double precision not null,
  visited_at timestamptz not null default now()
);

create index if not exists luwa_visit_events_visited_at_idx
  on public.luwa_visit_events (visited_at desc);

create index if not exists luwa_visit_events_location_idx
  on public.luwa_visit_events (country, city);

-- No direct browser access to raw events.
alter table public.luwa_visit_events enable row level security;
revoke all on table public.luwa_visit_events from anon, authenticated;

-- Browser-callable function: records one approximate visit event.
create or replace function public.record_luwa_visit(
  p_city text,
  p_country text,
  p_country_code text,
  p_lat double precision,
  p_lng double precision
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_city is null or length(trim(p_city)) = 0 or length(p_city) > 120 then
    raise exception 'invalid city';
  end if;
  if p_country is null or length(trim(p_country)) = 0 or length(p_country) > 120 then
    raise exception 'invalid country';
  end if;
  if p_lat is null or p_lat < -90 or p_lat > 90 or p_lng is null or p_lng < -180 or p_lng > 180 then
    raise exception 'invalid coordinates';
  end if;

  insert into public.luwa_visit_events(city, country, country_code, lat, lng)
  values (
    left(trim(p_city),120),
    left(trim(p_country),120),
    left(coalesce(trim(p_country_code),''),10),
    round(p_lat::numeric,1)::double precision,
    round(p_lng::numeric,1)::double precision
  );
end;
$$;

-- Returns aggregated city locations. p_days NULL = all time.
create or replace function public.get_luwa_visit_locations(p_days integer default null)
returns table (
  city text,
  country text,
  lat double precision,
  lng double precision,
  visits bigint,
  last_activity timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    e.city,
    e.country,
    e.lat,
    e.lng,
    count(*)::bigint as visits,
    max(e.visited_at) as last_activity
  from public.luwa_visit_events e
  where p_days is null
     or e.visited_at >= now() - make_interval(days => greatest(1, least(p_days, 3650)))
  group by e.city, e.country, e.lat, e.lng
  order by visits desc, e.country, e.city;
$$;

-- Only the two controlled RPC functions are public.
revoke all on function public.record_luwa_visit(text,text,text,double precision,double precision) from public;
revoke all on function public.get_luwa_visit_locations(integer) from public;
grant execute on function public.record_luwa_visit(text,text,text,double precision,double precision) to anon, authenticated;
grant execute on function public.get_luwa_visit_locations(integer) to anon, authenticated;

-- Explicitly keep raw table inaccessible to browser roles.
revoke select, insert, update, delete on public.luwa_visit_events from anon, authenticated;
